package com.ariseontech.joindesk.event.domain;

public enum JDEventType {
    ISSUE_CREATE,
    ISSUE_UPDATE,
    ISSUE_DELETE,
    ISSUE_COMMENT_CREATE,
    ISSUE_COMMENT_UPDATE,
    ISSUE_COMMENT_DELETE,
    ISSUE_ASSIGN,
    ISSUE_ATTACHMENT_CREATE,
    ISSUE_ATTACHMENT_DELETE
}
